### ISSUE TITLE
Remove binary files

### ISSUE THREAD

**Issue by ghost** [Daniele122898/Rem#1]
![](https://i.imgflip.com/1ch0z2.jpg)

GIT can't handle versioning of these files and thus including them is pointless.
This includes:

```
.idea/
ffmpeg-3.1.4-win64-static/
target/
ffmpeg.exe
ffprobe.exe
youtube-dl
```

**Comment by Daniele122898** [comment]
Thanks alot for the headsup! 

Fixed 👍
