### ISSUE TITLE
Do not explicitly call the GC

### ISSUE THREAD

**Issue by ghost** [Daniele122898/Rem#5]
Talking about:

``` java
private void garbage(MessageReceivedEvent e){
    if(e.getMessage().getAuthor().getID().equals("192750776005689344")) {
        System.gc();
        MsgUtils.sendMsg(e, "GC executed");
    }else{
        MsgUtils.sendMsg(e, "Only the Bot owner has permissions to use this command!");
    }
}
```

The GC knows what it's doing and is mostly smarter when it comes to determining an ideal moment for garbage collection. The `%gc` command in my bot was mostly for debugging purposes because i wanted to see if the bot allocates memory with references to itself (i.e. uncollectable by the GC). 

Generally spaking: Using `System.gc()` is considered bad practice.
Using it in production environments is a pretty good indicator of fundamentally broken code. Any code that depends on it for correctness is certainly broken; any that rely on it for performance are most likely broken.

Why?

1.) Different JVM's on different platforms may use different GC's. You never know _what_ your call will do or _if_ it will do anything at all (see 2).
2.) The JVM is free do ignore the `gc()` and just do nothing. (This is by design).
3.) You **don't** return memory to the system (in most cases). Even if the  GC manages to delete some objects the JVM is free to just leave the heap size as it is. (Example: After a GC you only use 25mb RAM but your heap still occupies 512mb because the JVM didn't resize it.).
4.) The combination of "you don't know what it does," "you don't know if it will help," and "you shouldn't need to call it anyway" is why so many people advise against using it.

see http://bugs.java.com/view_bug.do?bug_id=6668279

**Comment by Daniele122898** [comment]
Fixed! Thanks
