### ISSUE TITLE
RemListener rework

### ISSUE THREAD

**Issue by ghost** [Daniele122898/Rem#7]
Please do yourself a favor and remove that 90+ lines switch..case.

You should *really* consider moving to annotated classes.
Autoloading them is literally one line of code when using https://github.com/ronmamo/reflections.

Example:
```java
static Set<Class<?>> loadModules() {
    return new Reflections("com.serenity.rem").getTypesAnnotatedWith(YourCoolAnnotation.class);
}
```

**Comment by Daniele122898** [comment]
don't understand it. will leave it simple.
